# Maximum version of php for silverstripe behat is currently 7.3
jobs:
  include:
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE 4.x-dev"
        - REQUIRE_RECIPE_TESTING=^2
        - BEHAT_TEST=1
        - REQUIRE_GRAPHQL="^3"
    - php: 8.0
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE 4.x-dev"
        - REQUIRE_RECIPE_TESTING=^2
        - BEHAT_TEST=1
        - REQUIRE_GRAPHQL="^4"
