jobs:
  fast_finish: true
  include:
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
        - PHPSTAN_TEST=1
    - php: 7.4
      env:
        - DB=PGSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - COW_TEST=1
    - php: 7.4
      env:
        - DB=MYSQL
        - PDO=1
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_COVERAGE_TEST=1
    - php: 8.0
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - REQUIRE_GRAPHQL="^3"
    - php: 8.1.0
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - REQUIRE_GRAPHQL="^4"
